export * from './user-actions';
export * from './shopping-actions';

export const Action = {
    ERROR: "ERROR",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    SIGNUP: "SIGNUP",
    PROFILE: "PROFILE",

    DISSMISS: "DISSMISS",

    LANDING_PRODUCTS: "LANDING_PRODUCTS",
    PRODUCT_DETAILS: "PRODUCT_DETAILS",
    ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
    REMOVE_FROM_WISHLIST: "REMOVE_FROM_WISHLIST",

    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",

    ADDED_NEW_ADDRESS: "ADDED_NEW_ADDRESS",

    PLACE_ORDER: "PLACE_ORDER"

    
  };